name: Fix UI Template
description: Fix 사항이 있을 때 사용하는 템플릿
title: "[fix ui]: Fix 이슈 제목"
labels: ["fix"]

body:
  - type: input
    id: related-bug
    attributes:
      label: Related Bug(Optaional)
      description: 관련된 버그 이슈
      placeholder: "ex. #32, #23"
    validations:
      required: false
  - type: textarea
    id: before-fix
    attributes:
      label: Current State
      description: Fix 전(현재) 내용
      placeholder: "문제를 풀어도 경험치가 반영되지 않음"
    validations:
      required: true
  - type: textarea
    id: after-fix
    attributes:
      label: Current State
      description: Fix 후 내용
      placeholder: "문제를 풀면 경험치가 반영됨"
    validations:
      required: true
  - type: input
    id: expected-period
    attributes:
      label: 예상 작업 기간
      placeholder: ~ MM/DD(E) ex. ~ 07/12(화)
    validations:
      required: true
